log4j.rootLogger=INFO, console

# Console appender
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.Target=System.out
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{ISO8601} [%t] %-5p %c{1} - %m%n

# Debezium — reduce noise
log4j.logger.io.debezium=INFO
log4j.logger.org.apache.kafka=WARN
log4j.logger.io.netty=WARN
log4j.logger.com.grpc.cdc=INFO
